version: "3.9"

services:
  api:
    build: .
    container_name: edu-pipeline-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models/artifacts:/app/models/artifacts
    environment:
      - MODEL_DIR=/app/models/artifacts
      - LOG_LEVEL=INFO

  spark:
    image: bitnami/spark:3.5
    container_name: edu-pipeline-spark
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"

  spark-worker:
    image: bitnami/spark:3.5
    container_name: edu-pipeline-spark-worker
    depends_on:
      - spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
